### ISSUE TITLE
less unhandled exceptions in the log

### ISSUE THREAD

**Issue by funkyfuture** [robcast/digilib#2] opened 2017-08-10 13:14 UTC
we regularly encounter exceptions like the following in our logs:

```
25028817 [pool-1-thread-1] ERROR digilib.image.DocuImage  - Error closing ImageOutputStream!
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:708)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:242)
	at javax.imageio.stream.MemoryCacheImageOutputStream.flushBefore(MemoryCacheImageOutputStream.java:194)
	at javax.imageio.stream.MemoryCacheImageOutputStream.close(MemoryCacheImageOutputStream.java:180)
	at digilib.image.ImageLoaderDocuImage.writeImage(ImageLoaderDocuImage.java:548)
	at digilib.servlet.ServletOps.sendImage(ServletOps.java:358)
	at digilib.servlet.AsyncServletWorker.run(AsyncServletWorker.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Datenübergabe unterbrochen (broken pipe)
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 22 more
25028817 [pool-1-thread-1] ERROR digilib.image.DocuImage  - Error closing ImageOutputStream!
org.eclipse.jetty.io.EofException
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:192)
	at org.eclipse.jetty.io.WriteFlusher.flush(WriteFlusher.java:408)
	at org.eclipse.jetty.io.WriteFlusher.write(WriteFlusher.java:302)
	at org.eclipse.jetty.io.AbstractEndPoint.write(AbstractEndPoint.java:129)
	at org.eclipse.jetty.server.HttpConnection$SendCallback.process(HttpConnection.java:708)
	at org.eclipse.jetty.util.IteratingCallback.processing(IteratingCallback.java:246)
	at org.eclipse.jetty.util.IteratingCallback.iterate(IteratingCallback.java:208)
	at org.eclipse.jetty.server.HttpConnection.send(HttpConnection.java:480)
	at org.eclipse.jetty.server.HttpChannel.sendResponse(HttpChannel.java:768)
	at org.eclipse.jetty.server.HttpChannel.write(HttpChannel.java:801)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:147)
	at org.eclipse.jetty.server.HttpOutput.write(HttpOutput.java:140)
	at org.eclipse.jetty.server.HttpOutput.flush(HttpOutput.java:242)
	at javax.imageio.stream.MemoryCacheImageOutputStream.flushBefore(MemoryCacheImageOutputStream.java:194)
	at javax.imageio.stream.MemoryCacheImageOutputStream.close(MemoryCacheImageOutputStream.java:180)
	at digilib.image.ImageLoaderDocuImage.writeImage(ImageLoaderDocuImage.java:548)
	at digilib.servlet.ServletOps.sendImage(ServletOps.java:358)
	at digilib.servlet.AsyncServletWorker.run(AsyncServletWorker.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Datenübergabe unterbrochen (broken pipe)
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.eclipse.jetty.io.ChannelEndPoint.flush(ChannelEndPoint.java:170)
	... 22 more
25028819 [pool-1-thread-1] ERROR digilib.servlet.AsyncServletWorker  - Other error: 
java.lang.IndexOutOfBoundsException: pos < flushedPos!
	at javax.imageio.stream.ImageInputStreamImpl.seek(ImageInputStreamImpl.java:768)
	at com.sun.imageio.plugins.png.IDATOutputStream.finishChunk(PNGImageWriter.java:191)
	at com.sun.imageio.plugins.png.IDATOutputStream.deflate(PNGImageWriter.java:226)
	at com.sun.imageio.plugins.png.IDATOutputStream.finish(PNGImageWriter.java:251)
	at com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(PNGImageWriter.java:945)
	at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1158)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at digilib.image.ImageLoaderDocuImage.writeImage(ImageLoaderDocuImage.java:529)
	at digilib.servlet.ServletOps.sendImage(ServletOps.java:358)
	at digilib.servlet.AsyncServletWorker.run(AsyncServletWorker.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
25028819 [pool-1-thread-1] ERROR digilib.servlet.AsyncServletWorker  - Other error: 
java.lang.IndexOutOfBoundsException: pos < flushedPos!
	at javax.imageio.stream.ImageInputStreamImpl.seek(ImageInputStreamImpl.java:768)
	at com.sun.imageio.plugins.png.IDATOutputStream.finishChunk(PNGImageWriter.java:191)
	at com.sun.imageio.plugins.png.IDATOutputStream.deflate(PNGImageWriter.java:226)
	at com.sun.imageio.plugins.png.IDATOutputStream.finish(PNGImageWriter.java:251)
	at com.sun.imageio.plugins.png.PNGImageWriter.write_IDAT(PNGImageWriter.java:945)
	at com.sun.imageio.plugins.png.PNGImageWriter.write(PNGImageWriter.java:1158)
	at javax.imageio.ImageWriter.write(ImageWriter.java:615)
	at digilib.image.ImageLoaderDocuImage.writeImage(ImageLoaderDocuImage.java:529)
	at digilib.servlet.ServletOps.sendImage(ServletOps.java:358)
	at digilib.servlet.AsyncServletWorker.run(AsyncServletWorker.java:117)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

i guess this is caused by some filesystem related issue when digilib tries to store a downscaled version of an image. but the documentation doesn't tell where that would be, thus i can't investigate that location.

anyway, a logging messsage for humans is preferable.

**Comment by robcast** [comment] 2017-08-14 13:19
Digilib doesn't store downscaled images. It doesn't write to disk at all. Maybe I should add this fact to the documentation. Any proposals for a good spot?

I have seen exceptions somewhat like this in my logs. I have not been able to find the exact reason for the exception. I think it is caused by the web client starting a connection and then closing the connection before the image data was fully delivered.

**Comment by funkyfuture** [comment] 2017-08-22 13:45
> Any proposals for a good spot?

`digilib-short` seems appropriate.

> I think it is caused by the web client starting a connection and then closing the connection before the image data was fully delivered.

that seems plausible. unfortunatley we couldn't yet figure out which client does so. therefore a readable message, including timestamp, user-agent and ip would be helpful.

**Comment by robcast** [comment] 2017-08-22 18:01
>> I think it is caused by the web client starting a connection and then closing the connection before the image data was fully delivered.

> that seems plausible. unfortunatley we couldn't yet figure out which client does so. therefore a readable message, including timestamp, user-agent and ip would be helpful.

I am not sure if information about the request like user-agent and IP is available when the exception is thrown or caught. I'll check this.

**Closed** 2020-02-07 18:42 UTC
Labels: enhancement, low-priority
